import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import type { StaticImageData } from "next/image";

import Twitter from "../images/twitter.svg";
import Instagram from "../images/instagram.svg";
import Facebook from "../images/facebook.svg";
import Link from "next/link";

const Home: NextPage = () => {

  const twitterImage: StaticImageData = Twitter as StaticImageData;
  const instagramImage: StaticImageData = Instagram as StaticImageData;
  const facebookImage: StaticImageData = Facebook as StaticImageData;

  return (
    <>
      <Head>
        <title>Nostalgia Notes Records</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/nostalgia-logo.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.navbar}>
          <div className={styles.navbar__logo}>
            <Image
              src="/nostalgia-logo.svg"
              className={styles.logo_logo}
              alt="Nostalgia Notes Records Logo"
              width={100}
              height={100}
            />
            <h1 className={styles.navbar__name}>Nostalgia Notes Records</h1>
          </div>
          <div className={styles.navbar__links}>
            <span className={styles.navbar__link}>HOME</span>
          </div>
        </div>
        <div className={styles.background}>
          <div className={styles.background__image}></div>
          <div className={styles.background__opacity}></div>
        </div>
        <div className={styles.container}>
          <h1 className={styles.header}>Records Coming Soon!</h1>
          <span className={styles.content}>
            Welcome to Nostalgia Notes Records, a company dedicated to preserving the soundtracks of classic video games on vinyl. Our mission is to transport you back in time to the days when you first experienced these games, and to provide a tangible reminder of the emotions and memories that they evoke.
            <br/>
            <br/>
            While our catalog is still in development, we are hard at work curating a collection of beloved titles that will be sure to delight gamers and vinyl enthusiasts alike.
            <br/>
            <br/>
            We believe that the soundtracks of these games are an integral part of the experience, and deserve to be celebrated in their own right. By capturing these compositions on vinyl, we hope to create a unique and immersive way for gamers to revisit their favorite titles.
            <br/>
            <br/>
            Thank you for visiting our website, and we look forward to sharing more updates with you soon.
          </span>
        </div>
        <div className={styles.footer}>
          <div className={styles.social_media}>
            <div className={styles.social_media_group}>
              <Image
                src={twitterImage}
                alt="Twitter Logo"
                width={24}
                height={24}
              />
              <Link
                href="https://twitter.com/NostalNotesRecs"
                passHref
              >
                <span className={styles.social_media_link}>@NostalNotesRecs</span>
              </Link>
            </div>
            <div className={styles.social_media_group}>
              <Image
                src={instagramImage}
                alt="Instagram Logo"
                width={24}
                height={24}
              />
              <Link
                href="https://www.instagram.com/nostalnotesrecs/"
                passHref
              >
                <span className={styles.social_media_link}>nostalnotesrecs</span>
              </Link>
            </div>
            <div className={styles.social_media_group}>
              <Image
                src={facebookImage}
                alt="Facebook Logo"
                width={24}
                height={24}
              />
              <Link
                href="https://www.facebook.com/nostalgianotesrecords"
                passHref
              >
                <span className={styles.social_media_link}>nostalgianotesrecords</span>
              </Link>
            </div>
          </div>
          <div className={styles.copyright}>
            <span className={styles.copyright__text}>©2023 Nostalgia Notes Records, all rights reserved, Design by &nbsp;<Link href="https://maxmosier.com/" target="_blank" className={styles.design}>Max Mosier</Link></span>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
